### ISSUE TITLE
Add StartScreen to AppInfo

### ISSUE THREAD

**Issue by P3N-101** [sebastian-muthwill/powerapps-docstring#47]
As the StartScreen app variable is now available it should be documented.

In the attached documentation.py I have added the following;

```
start_screen = app_screen[1]["App As appinfo"].get("StartScreen")
```
at line 172 and the following in the # write app info block

```
  if start_screen != None:
            appinfo = self._extract_parts_from_propperty(start_screen)
            if appinfo[1] != None:
                self.md_file.new_paragraph(appinfo[1])
            self.md_file.new_line("")
            self.md_file.new_header(level=2, title="StartScreen")
            self.md_file.insert_code(appinfo[2],language='typescript')
            self.md_file.new_line("")
```
This also has some updates to Mermaid to work OOTB with Docusaurus, namely ==> becomes --> and screen names cannot have spaces, well I haven't worked out how to yet. Working on Datasources and Tests next :)

[documentation - Copy.txt](https://github.com/sebastian-muthwill/powerapps-docstring/files/7493625/documentation.-.Copy.txt)

**Comment by sebastian-muthwill** [comment]
Thx for your participation. I took over the changes for StartScreen. 

Is Docusaurus mermaid not supporting the ==> syntax? This is a standard for bald lines in mermaid. 
I check on this

**Comment by sebastian-muthwill** [comment]
The mermaid implementation was wrong. I changed it to the propper synthax based on mermaid documentations. 

Here is the new example how it will be represented with spaces in Screen names. [find example here](https://mermaid.live/edit#eyJjb2RlIjoiZ3JhcGggTFIgIFxuV2VsY29tZVNjcmVlbihXZWxjb21lU2NyZWVuKSAtLT4gSG9tZVBvcFVwc1NjcmVlbihIb21lUG9wVXBzU2NyZWVuKSAgXG5Ib21lU2NyZWVuKEhvbWVTY3JlZW4pIC0tPiBTa2V0Y2hTY3JlZW4oU2tldGNoIFNjcmVlbikgIFxuSG9tZVNjcmVlbihIb21lU2NyZWVuKSAtLT4gQ2FtZXJhU2NyZWVuKENhbWVyYVNjcmVlbikgIFxuSG9tZVNjcmVlbihIb21lU2NyZWVuKSAtLT4gRW1haWxTY3JlZW4oRW1haWxTY3JlZW4pICBcbkhvbWVTY3JlZW4oSG9tZVNjcmVlbikgLS0-IEF0dGFjaG1lbnRzU2NyZWVuKEF0dGFjaG1lbnRzU2NyZWVuKSAgXG5Ib21lU2NyZWVuKEhvbWVTY3JlZW4pIC0tPiBFeHBvcnRTY3JlZW4oRXhwb3J0U2NyZWVuKSAgXG5Ib21lU2NyZWVuKEhvbWVTY3JlZW4pIC0tPiBIb21lUG9wVXBzU2NyZWVuKEhvbWVQb3BVcHNTY3JlZW4pICBcblNrZXRjaFNjcmVlbihTa2V0Y2ggU2NyZWVuKSAtLT4gSG9tZVNjcmVlbihIb21lU2NyZWVuKSAgXG5Ta2V0Y2hTY3JlZW4oU2tldGNoIFNjcmVlbikgLS0-IENhbWVyYVNjcmVlbihDYW1lcmFTY3JlZW4pICBcbkNhbWVyYVNjcmVlbihDYW1lcmFTY3JlZW4pIC0tPiBIb21lU2NyZWVuKEhvbWVTY3JlZW4pICBcbkNhbWVyYVNjcmVlbihDYW1lcmFTY3JlZW4pIC0tPiBTa2V0Y2hTY3JlZW4oU2tldGNoIFNjcmVlbikgIFxuRW1haWxTY3JlZW4oRW1haWxTY3JlZW4pIC0tPiBDb25maXJtU2NyZWVuKENvbmZpcm1TY3JlZW4pICBcbkNvbmZpcm1TY3JlZW4oQ29uZmlybVNjcmVlbikgLS0-IEhvbWVTY3JlZW4oSG9tZVNjcmVlbikgIFxuQ29uZmlybVNjcmVlbihDb25maXJtU2NyZWVuKSAtLT4gRm9sbG93VXBTY3JlZW4oRm9sbG93VXBTY3JlZW4pICBcbkNvbmZpcm1TY3JlZW4oQ29uZmlybVNjcmVlbikgLS0-IFdlbGNvbWVTY3JlZW4oV2VsY29tZVNjcmVlbikgIFxuRXhwb3J0U2NyZWVuKEV4cG9ydFNjcmVlbikgLS0-IEhvbWVTY3JlZW4oSG9tZVNjcmVlbikgIFxuRXhwb3J0U2NyZWVuKEV4cG9ydFNjcmVlbikgLS0-IEV4cG9ydFBvcFVwc1NjcmVlbihFeHBvcnRQb3BVcHNTY3JlZW4pICBcbkZvbGxvd1VwU2NyZWVuKEZvbGxvd1VwU2NyZWVuKSAtLT4gRm9sbG93VXBUaW1lc1NjcmVlbihGb2xsb3dVcFRpbWVzU2NyZWVuKSAgXG5Gb2xsb3dVcFRpbWVzU2NyZWVuKEZvbGxvd1VwVGltZXNTY3JlZW4pIC0tPiBDb25maXJtU2NyZWVuKENvbmZpcm1TY3JlZW4pICBcbkhvbWVQb3BVcHNTY3JlZW4oSG9tZVBvcFVwc1NjcmVlbikgLS0-IEhvbWVTY3JlZW4oSG9tZVNjcmVlbikgIFxuRXhwb3J0UG9wVXBzU2NyZWVuKEV4cG9ydFBvcFVwc1NjcmVlbikgLS0-IEV4cG9ydFNjcmVlbihFeHBvcnRTY3JlZW4pICBcbkV4cG9ydFBvcFVwc1NjcmVlbihFeHBvcnRQb3BVcHNTY3JlZW4pIC0tPiBDb25maXJtU2NyZWVuKENvbmZpcm1TY3JlZW4pIiwibWVybWFpZCI6IntcbiAgXCJ0aGVtZVwiOiBcImRlZmF1bHRcIlxufSIsInVwZGF0ZUVkaXRvciI6ZmFsc2UsImF1dG9TeW5jIjp0cnVlLCJ1cGRhdGVEaWFncmFtIjpmYWxzZX0)
[![](https://mermaid.ink/img/eyJjb2RlIjoiZ3JhcGggTFIgIFxuV2VsY29tZVNjcmVlbihXZWxjb21lU2NyZWVuKSAtLT4gSG9tZVBvcFVwc1NjcmVlbihIb21lUG9wVXBzU2NyZWVuKSAgXG5Ib21lU2NyZWVuKEhvbWVTY3JlZW4pIC0tPiBTa2V0Y2hTY3JlZW4oU2tldGNoIFNjcmVlbikgIFxuSG9tZVNjcmVlbihIb21lU2NyZWVuKSAtLT4gQ2FtZXJhU2NyZWVuKENhbWVyYVNjcmVlbikgIFxuSG9tZVNjcmVlbihIb21lU2NyZWVuKSAtLT4gRW1haWxTY3JlZW4oRW1haWxTY3JlZW4pICBcbkhvbWVTY3JlZW4oSG9tZVNjcmVlbikgLS0-IEF0dGFjaG1lbnRzU2NyZWVuKEF0dGFjaG1lbnRzU2NyZWVuKSAgXG5Ib21lU2NyZWVuKEhvbWVTY3JlZW4pIC0tPiBFeHBvcnRTY3JlZW4oRXhwb3J0U2NyZWVuKSAgXG5Ib21lU2NyZWVuKEhvbWVTY3JlZW4pIC0tPiBIb21lUG9wVXBzU2NyZWVuKEhvbWVQb3BVcHNTY3JlZW4pICBcblNrZXRjaFNjcmVlbihTa2V0Y2ggU2NyZWVuKSAtLT4gSG9tZVNjcmVlbihIb21lU2NyZWVuKSAgXG5Ta2V0Y2hTY3JlZW4oU2tldGNoIFNjcmVlbikgLS0-IENhbWVyYVNjcmVlbihDYW1lcmFTY3JlZW4pICBcbkNhbWVyYVNjcmVlbihDYW1lcmFTY3JlZW4pIC0tPiBIb21lU2NyZWVuKEhvbWVTY3JlZW4pICBcbkNhbWVyYVNjcmVlbihDYW1lcmFTY3JlZW4pIC0tPiBTa2V0Y2hTY3JlZW4oU2tldGNoIFNjcmVlbikgIFxuRW1haWxTY3JlZW4oRW1haWxTY3JlZW4pIC0tPiBDb25maXJtU2NyZWVuKENvbmZpcm1TY3JlZW4pICBcbkNvbmZpcm1TY3JlZW4oQ29uZmlybVNjcmVlbikgLS0-IEhvbWVTY3JlZW4oSG9tZVNjcmVlbikgIFxuQ29uZmlybVNjcmVlbihDb25maXJtU2NyZWVuKSAtLT4gRm9sbG93VXBTY3JlZW4oRm9sbG93VXBTY3JlZW4pICBcbkNvbmZpcm1TY3JlZW4oQ29uZmlybVNjcmVlbikgLS0-IFdlbGNvbWVTY3JlZW4oV2VsY29tZVNjcmVlbikgIFxuRXhwb3J0U2NyZWVuKEV4cG9ydFNjcmVlbikgLS0-IEhvbWVTY3JlZW4oSG9tZVNjcmVlbikgIFxuRXhwb3J0U2NyZWVuKEV4cG9ydFNjcmVlbikgLS0-IEV4cG9ydFBvcFVwc1NjcmVlbihFeHBvcnRQb3BVcHNTY3JlZW4pICBcbkZvbGxvd1VwU2NyZWVuKEZvbGxvd1VwU2NyZWVuKSAtLT4gRm9sbG93VXBUaW1lc1NjcmVlbihGb2xsb3dVcFRpbWVzU2NyZWVuKSAgXG5Gb2xsb3dVcFRpbWVzU2NyZWVuKEZvbGxvd1VwVGltZXNTY3JlZW4pIC0tPiBDb25maXJtU2NyZWVuKENvbmZpcm1TY3JlZW4pICBcbkhvbWVQb3BVcHNTY3JlZW4oSG9tZVBvcFVwc1NjcmVlbikgLS0-IEhvbWVTY3JlZW4oSG9tZVNjcmVlbikgIFxuRXhwb3J0UG9wVXBzU2NyZWVuKEV4cG9ydFBvcFVwc1NjcmVlbikgLS0-IEV4cG9ydFNjcmVlbihFeHBvcnRTY3JlZW4pICBcbkV4cG9ydFBvcFVwc1NjcmVlbihFeHBvcnRQb3BVcHNTY3JlZW4pIC0tPiBDb25maXJtU2NyZWVuKENvbmZpcm1TY3JlZW4pIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifSwidXBkYXRlRWRpdG9yIjpmYWxzZSwiYXV0b1N5bmMiOnRydWUsInVwZGF0ZURpYWdyYW0iOmZhbHNlfQ)](https://mermaid.live/edit#eyJjb2RlIjoiZ3JhcGggTFIgIFxuV2VsY29tZVNjcmVlbihXZWxjb21lU2NyZWVuKSAtLT4gSG9tZVBvcFVwc1NjcmVlbihIb21lUG9wVXBzU2NyZWVuKSAgXG5Ib21lU2NyZWVuKEhvbWVTY3JlZW4pIC0tPiBTa2V0Y2hTY3JlZW4oU2tldGNoIFNjcmVlbikgIFxuSG9tZVNjcmVlbihIb21lU2NyZWVuKSAtLT4gQ2FtZXJhU2NyZWVuKENhbWVyYVNjcmVlbikgIFxuSG9tZVNjcmVlbihIb21lU2NyZWVuKSAtLT4gRW1haWxTY3JlZW4oRW1haWxTY3JlZW4pICBcbkhvbWVTY3JlZW4oSG9tZVNjcmVlbikgLS0-IEF0dGFjaG1lbnRzU2NyZWVuKEF0dGFjaG1lbnRzU2NyZWVuKSAgXG5Ib21lU2NyZWVuKEhvbWVTY3JlZW4pIC0tPiBFeHBvcnRTY3JlZW4oRXhwb3J0U2NyZWVuKSAgXG5Ib21lU2NyZWVuKEhvbWVTY3JlZW4pIC0tPiBIb21lUG9wVXBzU2NyZWVuKEhvbWVQb3BVcHNTY3JlZW4pICBcblNrZXRjaFNjcmVlbihTa2V0Y2ggU2NyZWVuKSAtLT4gSG9tZVNjcmVlbihIb21lU2NyZWVuKSAgXG5Ta2V0Y2hTY3JlZW4oU2tldGNoIFNjcmVlbikgLS0-IENhbWVyYVNjcmVlbihDYW1lcmFTY3JlZW4pICBcbkNhbWVyYVNjcmVlbihDYW1lcmFTY3JlZW4pIC0tPiBIb21lU2NyZWVuKEhvbWVTY3JlZW4pICBcbkNhbWVyYVNjcmVlbihDYW1lcmFTY3JlZW4pIC0tPiBTa2V0Y2hTY3JlZW4oU2tldGNoIFNjcmVlbikgIFxuRW1haWxTY3JlZW4oRW1haWxTY3JlZW4pIC0tPiBDb25maXJtU2NyZWVuKENvbmZpcm1TY3JlZW4pICBcbkNvbmZpcm1TY3JlZW4oQ29uZmlybVNjcmVlbikgLS0-IEhvbWVTY3JlZW4oSG9tZVNjcmVlbikgIFxuQ29uZmlybVNjcmVlbihDb25maXJtU2NyZWVuKSAtLT4gRm9sbG93VXBTY3JlZW4oRm9sbG93VXBTY3JlZW4pICBcbkNvbmZpcm1TY3JlZW4oQ29uZmlybVNjcmVlbikgLS0-IFdlbGNvbWVTY3JlZW4oV2VsY29tZVNjcmVlbikgIFxuRXhwb3J0U2NyZWVuKEV4cG9ydFNjcmVlbikgLS0-IEhvbWVTY3JlZW4oSG9tZVNjcmVlbikgIFxuRXhwb3J0U2NyZWVuKEV4cG9ydFNjcmVlbikgLS0-IEV4cG9ydFBvcFVwc1NjcmVlbihFeHBvcnRQb3BVcHNTY3JlZW4pICBcbkZvbGxvd1VwU2NyZWVuKEZvbGxvd1VwU2NyZWVuKSAtLT4gRm9sbG93VXBUaW1lc1NjcmVlbihGb2xsb3dVcFRpbWVzU2NyZWVuKSAgXG5Gb2xsb3dVcFRpbWVzU2NyZWVuKEZvbGxvd1VwVGltZXNTY3JlZW4pIC0tPiBDb25maXJtU2NyZWVuKENvbmZpcm1TY3JlZW4pICBcbkhvbWVQb3BVcHNTY3JlZW4oSG9tZVBvcFVwc1NjcmVlbikgLS0-IEhvbWVTY3JlZW4oSG9tZVNjcmVlbikgIFxuRXhwb3J0UG9wVXBzU2NyZWVuKEV4cG9ydFBvcFVwc1NjcmVlbikgLS0-IEV4cG9ydFNjcmVlbihFeHBvcnRTY3JlZW4pICBcbkV4cG9ydFBvcFVwc1NjcmVlbihFeHBvcnRQb3BVcHNTY3JlZW4pIC0tPiBDb25maXJtU2NyZWVuKENvbmZpcm1TY3JlZW4pIiwibWVybWFpZCI6IntcbiAgXCJ0aGVtZVwiOiBcImRlZmF1bHRcIlxufSIsInVwZGF0ZUVkaXRvciI6ZmFsc2UsImF1dG9TeW5jIjp0cnVlLCJ1cGRhdGVEaWFncmFtIjpmYWxzZX0)
